Lagde ny error side
echo-webkom/echo-web-mono pull request #1266
Opened 2024-01-22 17:27 UTC by xxSwarnika

## Why did you create this PR?
Det var på Trello kortet mitt :)

Den tidligere error meldingen var ikke så fin, så prøvde å forbedre den til noe litt bedre og enklere
## How did you solve the problem?
endret på utseendet.

la inn header og en overskrift med litt tekst under og en gif for utseendet.

2024-01-22 18:09 UTC, omfj commented
Tror ikke du mente å pushe den jordskjelv greia?

2024-01-25 11:19 UTC, omfj requested changes

2024-01-25 11:19 UTC, omfj commented on apps/web/src/app/(default)/page.tsx
> +import { notFound } from "next/navigation";
```suggestion
```

2024-01-25 11:19 UTC, omfj commented on apps/web/src/app/(default)/page.tsx
> +
```suggestion

```

2024-01-25 11:19 UTC, omfj commented on apps/web/src/app/not-found.tsx
> +      <Heading className="text-center"> PAGE NOT FOUND</Heading>
```suggestion
      <Heading className="text-center">PAGE NOT FOUND</Heading>
```

Jeg tenker kanskje det også kunne stå på norsk? Vet ikke hva andre tenker.

2024-01-25 11:19 UTC, omfj commented on apps/web/src/app/not-found.tsx
> +      <div className="flex w-full flex-grow flex-col py-10 text-center after:content-['\1F610']">
Hvorfor `after:content-['\1F610']`?

2024-09-08 10:07 UTC, closed without merging

2024-09-08 13:23 UTC, Herwal commented
skal ditte fortsatt gjerast?