Profile pictures
echo-webkom/echo-web-mono pull request #1276
Opened 2024-01-23 19:22 UTC by bocianowski1

## Why did you create this PR?

For å ha mulighet for å ha profilbilder. Fortsatt mange ting som kan forbedres utseendemessig: f eks croppe bilder eller bedre styling generelt.

## How did you solve the problem?

Bruker Azure Blob Storage til å lagre filer. Laget et API i go og deployet til en Azure Function App. Koden for function ligger i [echo-images](/echo-webkom/echo-images).

2024-01-23 21:01 UTC, omfj requested changes
HEF10!! 🚀🚀

2024-01-23 21:01 UTC, omfj commented on apps/web/src/actions/images.ts
> +      `https://echo-images.azurewebsites.net/api/images?userId=${userId}`,
Er vel også her vi burde bruke next sin `no-store`

2024-01-23 21:02 UTC, omfj commented
Testene feiler fordi vi har en test for å lagre bruker info, og din knapp for profilbilde conflicter med knappen for å lagre brukerinfo.

2024-01-23 21:29 UTC, omfj requested changes

2024-01-25 23:25 UTC, Herwal commented on packages/echogram/src/index.ts
> +      }
Er dette error melding som brukeren får? da kunne vi kanskje nevnt max filesize i returnen

2024-01-25 23:44 UTC, omfj commented on packages/echogram/src/index.ts
> +      }
Backer! Veldig lurt

2024-01-29 16:05 UTC, 0Zeno approved these changes
![KnucklesApprovedGIF](https://github.com/echo-webkom/echo-web-mono/assets/145581496/4690baf8-ddae-4e7c-9910-665fe2fccf86)

2024-01-31 11:32 UTC, bocianowski1 commented on packages/echogram/src/index.ts
> +      }
Nice! La det til

2024-01-31 12:40 UTC, merged