Malin/hyggkom handleliste
echo-webkom/echo-web-mono pull request #1281
Opened 2024-01-24 16:25 UTC by KristianElde

## Why did you create this PR?

## How did you solve the problem?

2024-01-30 12:14 UTC, omfj commented on packages/db/schemas/users_to_shopping_list_items.ts
> +    pk: primaryKey(table.userId, table.itemId),
```suggestion
    pk: primaryKey({ columns: [table.userId, table.itemId] }),
```

2024-01-30 12:14 UTC, omfj commented on packages/db/schemas/users_to_shopping_list_items.ts
> +  userId: one(users, {
```suggestion
  user: one(users, {
```

2024-01-30 12:14 UTC, omfj commented on packages/db/schemas/users_to_shopping_list_items.ts
> +  itemId: one(shoppingListItems, {
```suggestion
  item: one(shoppingListItems, {
```

2024-01-30 12:14 UTC, omfj commented on packages/db/schemas/users_to_shopping_list_items.ts
> +  "users-to-shopping-list-items",
```suggestion
  "users_to_shopping_list_items",
```

2024-01-30 12:15 UTC, omfj commented on packages/db/schemas/shopping-list-items.ts
> +  userId: one(users, {
```suggestion
  user: one(users, {
```

2024-01-30 12:16 UTC, omfj commented on apps/web/src/components/hyggkom-shopping-list.tsx
> +                  <IoTrashBinOutline></IoTrashBinOutline>
```suggestion
                  <IoTrashBinOutline />
```

2024-01-30 12:16 UTC, omfj commented on apps/web/src/app/(default)/handleliste/page.tsx
> +    .groupBy(shoppingListItems.id);
Burde også være egen funksjon

2024-01-30 12:18 UTC, omfj commented on apps/web/src/actions/get-color-like-button.ts
> +"use server";
Denne filen trengs egentlig ikke.

2024-01-30 21:13 UTC, omfj requested changes

2024-01-30 21:13 UTC, omfj commented on apps/web/src/lib/schemas/hyggkomShoppingList.ts
> +import { z } from "zod";
rename denne filen

2024-01-30 21:28 UTC, omfj approved these changes

2024-01-30 21:28 UTC, omfj commented on apps/web/src/data/shopping-list-item/queries.ts
> +      });
```suggestion
      return await db.query.shoppingListItems.findMany({
        with: { likes: true },
      }).catch(() => []);
```

2024-01-31 09:53 UTC, izaaksarnecki1 reviewed
Ser bra ut spør du meg <3

2024-01-31 09:56 UTC, omfj approved these changes
Nice! 🚀🚀⚡️⚡️

2024-01-31 10:14 UTC, merged