Download ics
echo-webkom/echo-web-mono pull request #1316
Opened 2024-01-28 21:09 UTC by omfj

Download ics

2024-01-29 09:47 UTC, kfalvestad requested changes

2024-01-29 09:47 UTC, kfalvestad commented on apps/web/src/app/api/calendar/route.ts
> +  const happenings = await fetchAllHappenings();
Denne fetcher alle tidligere arrangementer også. Kanskje bruke fetchFiltered, eller bare kommende?

2024-01-29 11:13 UTC, omfj commented
Tenkte på det, men sånn som jeg tror det funker, så vil kalenderen lese dette endepunktet rutinemessing, og da tror jeg de gamle arrangementene blir fjernet. Tror ikke vi vil det. Funker vel relativt likt som en RSS-feed.

2024-02-11 22:39 UTC, omfj commented
@kfalvestad Flytter den bak `/beta/calendar`, også flytter jeg den heller til `/for-studenter/arrangementer` når jeg vet hvordan jeg vil at den skal se ut.

Selve api-endepunktet burde være ferdig.

2024-02-11 22:40 UTC, omfj commented on apps/web/src/app/api/calendar/route.ts
> +  const happenings = await fetchAllHappenings();
Nei, er samme. `fetchFiltered` bruker `fetchAllHappenings` uansett.

2024-02-12 08:12 UTC, kfalvestad approved these changes

2024-02-12 08:36 UTC, merged