delete company description from sanity
echo-webkom/echo-web-mono pull request #1526
Opened 2024-03-02 21:52 UTC by izaaksarnecki1

## Why did you create this PR?

Var et trello kort om å fjerne description fra bedrift på sanity.  

## How did you solve the problem?

Fjernet det fra schema.

2024-03-03 11:08 UTC, omfj commented
Nice. Er det noen zod schemas eller queries som fortsatt bruker description?

2024-03-03 12:46 UTC, izaaksarnecki1 commented
> Nice. Er det noen zod schemas eller queries som fortsatt bruker description?

Skulle ha tenkt over det. Sjekker opp i det.

2024-03-03 16:52 UTC, omfj requested changes

2024-03-03 16:52 UTC, omfj commented on apps/web/src/sanity/happening/schemas.ts
> -  company: companySchema.omit({ description: true }).nullable(),
```
company: companySchema.nullable(),
```

2024-03-04 09:28 UTC, omfj commented
`pnpm format` burde fikse det siste.

2024-03-04 12:57 UTC, merged