Hermann/csv
echo-webkom/echo-web-mono pull request #1731
Opened 2024-04-03 16:05 UTC by Herwal

## Why did you create this PR?
For å kunne redigere hva csv skal inneholde

Å kunne velge kolonner til csv.

## How did you solve the problem?
Filtrerer valgte kolonner gjennom dropdown meny, og gir det til download csv knappen.

2024-04-03 20:22 UTC, omfj requested changes
Ser bra veldig bra ut! Er noen kommentarer, også må du huske å kjøre `pnpm format`.

Eller var det sånn at `pnpm format` ikke funket til deg? Da kan jeg kjøre det for deg.

2024-04-03 20:22 UTC, omfj commented on apps/web/src/app/(default)/dashbord/[slug]/page.tsx
> +  }
Kan man ikke heller bytte ut querien over med denne? De henter jo så å si det samme.

```suggestion
  const happening = await getHappeningCsvData(happening.id);
  
  if (!happening) {
    return notFound();
  }
```

2024-04-03 20:22 UTC, omfj commented on apps/web/src/app/(default)/dashbord/[slug]/page.tsx
> +            // registrationRecords={getCsvData}
Kan fjerne denne.

2024-04-03 20:22 UTC, omfj commented on apps/web/src/lib/csv.ts
> +      if (Object.prototype.hasOwnProperty.call(obj, header)) {
Vet ikke om det funker, men hadde ikke (kode under) vært det samme?

```suggestion
      if (header in obj) {
```

2024-04-03 20:22 UTC, omfj commented on apps/web/src/lib/csv.ts
> +export const toCsv = (happening: Exclude<Awaited<ReturnType<typeof getHappeningCsvData>>, undefined>, selectedHeaders: Array<string>): string => {
Kunne du ha lagt til noen unit-tester for denne funksjoner?

2024-04-03 20:22 UTC, omfj commented on apps/web/src/components/registration-table.tsx
> +}
Denne ser ikke ut til å bli brukt noe sted.

```suggestion
```

2024-04-03 20:22 UTC, omfj commented on apps/web/src/components/registration-table.tsx
> +        <div className="flex flex-col items-center gap-4 pb-2 pt-2 md:flex-row md:pb-4">
Kunne vi ha lagt til noe padding på sidene (`px`) her og?

![CleanShot 2024-04-03 at 22 20 47@2x](https://github.com/echo-webkom/echo-web-mono/assets/32321558/7c617c79-e81f-4272-aa50-9ce6600f4aa9)

2024-04-03 20:26 UTC, Herwal commented
Skal kunne kjøre format tror eg, glemte at auto formatten var feil 😭

Sendt frå Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ole Magnus Fon Johnsen ***@***.***>
Sent: Wednesday, April 3, 2024 10:22:59 PM
To: echo-webkom/echo-web-mono ***@***.***>
Cc: Hermann Holstad Walaunet ***@***.***>; Author ***@***.***>
Subject: Re: [echo-webkom/echo-web-mono] Hermann/csv (PR #1731)


@omfj requested changes on this pull request.

Ser bra veldig bra ut! Er noen kommentarer, også må du huske å kjøre pnpm format.

Eller var det sånn at pnpm format ikke funket til deg? Da kan jeg kjøre det for deg.

________________________________

In apps/web/src/app/(default)/dashbord/[slug]/page.tsx<https://github.com/echo-webkom/echo-web-mono/pull/1731#discussion_r1550381130>:

> +  const getCsvData = await getHappeningCsvData(happening.id);
+  if (!getCsvData) {
+    return notFound();
+  }


Kan man ikke heller bytte ut querien over med denne? De henter jo så å si det samme.

⬇️ Suggested change

-  const getCsvData = await getHappeningCsvData(happening.id);
-  if (!getCsvData) {
-    return notFound();
-  }
+  const happening = await getHappeningCsvData(happening.id);
+
+  if (!happening) {
+    return notFound();
+  }


________________________________

In apps/web/src/app/(default)/dashbord/[slug]/page.tsx<https://github.com/echo-webkom/echo-web-mono/pull/1731#discussion_r1550381446>:

> @@ -119,6 +125,8 @@ export default async function EventDashboard({ params }: Props) {
         <div className="flex flex-col gap-3">
           <h2 className="text-3xl font-semibold">Registrerte</h2>
           <RegistrationTable
+            // registrationRecords={getCsvData}


Kan fjerne denne.

________________________________

In apps/web/src/lib/csv.ts<https://github.com/echo-webkom/echo-web-mono/pull/1731#discussion_r1550389726>:

>      obj.Studieretning = r.user.degreeId ?? "Ingen studieretning";
     obj.Grunn = r.unregisterReason ?? "";

-    for (const question of happening.questions) {
-      const answer = answers.find((a) => a.questionId === question.id)?.answer;
-
-      const formattedAnswer = Array.isArray(answer) ? answer.join(", ") : answer ?? "";
-
-      obj[question.title] = formattedAnswer;
-    }
+    const filteredObj: Record<string, string> = {};
+    selectedHeaders.forEach((header) => {
+      if (header === "Alternativ Epost") {
+        header = "Epost";
+      }
+      if (Object.prototype.hasOwnProperty.call(obj, header)) {


Vet ikke om det funker, men hadde ikke (kode under) vært det samme?

⬇️ Suggested change

-      if (Object.prototype.hasOwnProperty.call(obj, header)) {
+      if (header in obj) {


________________________________

In apps/web/src/lib/csv.ts<https://github.com/echo-webkom/echo-web-mono/pull/1731#discussion_r1550390323>:

> @@ -8,34 +8,39 @@ const parser = new Parser({
   withBOM: true,
 });

-export const toCsv = (
-  happening: Exclude<Awaited<ReturnType<typeof getHappeningCsvData>>, undefined>,
-): string => {
+export const toCsv = (happening: Exclude<Awaited<ReturnType<typeof getHappeningCsvData>>, undefined>, selectedHeaders: Array<string>): string => {


Kunne du ha lagt til noen unit-tester for denne funksjoner?

________________________________

In apps/web/src/components/registration-table.tsx<https://github.com/echo-webkom/echo-web-mono/pull/1731#discussion_r1550393160>:

> +export function useTableColumns(questions: Array<Question>, selectUserSchema: ZodTypeAny) {
+  const [columns, setColumns] = useState<Array<string>>([]);
+
+  useEffect(() => {
+    const obj = zodKeys(selectUserSchema);
+    const columns = [...Object.keys(obj), ...questions.map((question) => question.title)];
+    setColumns(columns);
+  }, [questions, selectUserSchema]);
+
+  return columns;
+}


Denne ser ikke ut til å bli brukt noe sted.

⬇️ Suggested change

-export function useTableColumns(questions: Array<Question>, selectUserSchema: ZodTypeAny) {
-  const [columns, setColumns] = useState<Array<string>>([]);
-
-  useEffect(() => {
-    const obj = zodKeys(selectUserSchema);
-    const columns = [...Object.keys(obj), ...questions.map((question) => question.title)];
-    setColumns(columns);
-  }, [questions, selectUserSchema]);
-
-  return columns;
-}


________________________________

In apps/web/src/components/registration-table.tsx<https://github.com/echo-webkom/echo-web-mono/pull/1731#discussion_r1550405091>:

>    return (
     <div className="h-full w-full overflow-y-auto rounded-lg border shadow-md">
       <div className="overflow-y-auto">
-        <div className="flex flex-col items-center gap-4 p-4 md:flex-row">
+        <div className="flex flex-col items-center gap-4 pb-2 pt-2 md:flex-row md:pb-4">


Kunne vi ha lagt til noe padding på sidene (px) her og?

***@***.*** (view on web)<https://github.com/echo-webkom/echo-web-mono/assets/32321558/7c617c79-e81f-4272-aa50-9ce6600f4aa9>

—
Reply to this email directly, view it on GitHub<https://github.com/echo-webkom/echo-web-mono/pull/1731#pullrequestreview-1977849008>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXMMULKCIXFSTCCOZ666DH3Y3RQKHAVCNFSM6AAAAABFVTQGXOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNZXHA2DSMBQHA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-03 22:10 UTC, Herwal commented on apps/web/src/app/(default)/dashbord/[slug]/page.tsx
> +  }
Er dette bare et navnebytte? Der er en annen variabel som allerede heter happening i funksjonen over, EventDashboard

2024-04-03 22:10 UTC, Herwal commented on apps/web/src/lib/csv.ts
> +      if (Object.prototype.hasOwnProperty.call(obj, header)) {
Jo de funket, nice der gitt eg ned et rabbithole ass

2024-04-03 22:11 UTC, Herwal commented on apps/web/src/components/registration-table.tsx
> +}
ble indeed ikke brukt

2024-04-03 22:18 UTC, Herwal commented on apps/web/src/app/(default)/dashbord/[slug]/page.tsx
> +  }
Også, var greia med formatteringen bare CRLF og LF?

2024-04-04 10:29 UTC, omfj commented on apps/web/src/app/(default)/dashbord/[slug]/page.tsx
> +  }
Så å si bare et navnebytte, ha. Du bare fjerner fetchen over og bytter ut med med csv.

Var noe med LF og CRLF med formateringen, ja.

2024-04-04 22:31 UTC, omfj approved these changes
<img src="https://media0.giphy.com/media/l2Sq5GffrCyUMEXjW/giphy.gif"/>

2024-04-05 12:11 UTC, merged