Nixengh/calendar
echo-webkom/echo-web-mono pull request #2267
Opened 2024-09-24 15:13 UTC by NixEngh

La til månedskalender og litt animasjon/nedlastingsknapp til arrangementer siden.

2024-09-25 09:29 UTC, omfj commented on apps/web/src/app/(default)/for-studenter/arrangementer/page.tsx
> +  const calendarEvents = happeningsToCalendarEvent(happenings).concat(
Nice, smart.

2024-09-25 09:39 UTC, omfj requested changes

2024-09-25 09:39 UTC, omfj commented on apps/web/src/components/calendar/days-calendar.tsx
> +  }, [setWeekText, startDate, steps, week]);
Dette trenger vel ikke å være en `useEffect`. Du kan bare si:

```
const weekText = `Uke ${week()}`
```

2024-09-25 09:39 UTC, omfj commented on apps/web/src/components/calendar/month-calendar.tsx
> +      setMonthText(`${months[getMonth(month)]} ${month.getFullYear()}`);
Samme her som over.

2024-09-25 10:23 UTC, omfj commented on apps/web/src/components/calendar/month-calendar.tsx
> +      setMonthText(`${months[getMonth(month)]} ${month.getFullYear()}`);
Glem det.

2024-09-25 10:35 UTC, 0Zeno commented on apps/web/src/components/calendar/month-calendar.tsx
> +                "flex h-10 items-center justify-end border-b border-muted-foreground px-2 py-6",
burde ikke fargen på borderen være lik som fargen til ukeskalenderen. Tror det er border-border

2024-09-25 14:32 UTC, omfj requested changes

2024-09-25 14:32 UTC, omfj commented on apps/web/package.json
> +    "@radix-ui/react-tabs": "^1.1.0",
```suggestion
    "@radix-ui/react-tabs": "1.1.0",
```

2024-09-25 17:30 UTC, omfj commented
`pnpm install` for å oppdatere lock filen.

2024-09-26 11:32 UTC, omfj approved these changes
kjørrrrrrrrrrrrrrr 🚀 🚀 🚀 🚀 🚀 🚀

2024-09-26 11:32 UTC, merged