seo-improvement
echo-webkom/echo-web-mono pull request #2292
Opened 2024-10-02 14:52 UTC by jesperkha

La til metadata for hver side som trenger det. La til dynamisk description tag for bedpress/jobb/osv.

2024-10-02 17:53 UTC, omfj commented
Du trenger faktisk ikke den hjelpe-funksjonen til å sette icon osv. Alle sider inn i en `layout.tsx` vil få de automatisk.

2024-10-08 11:44 UTC, 0Zeno commented on apps/web/src/app/(default)/arrangement/[slug]/page.tsx
> +    `Ny event "${event.title}" med ${event.company?.name},
Nytt arrangement*****

2024-10-08 11:47 UTC, jesperkha commented on apps/web/src/app/(default)/arrangement/[slug]/page.tsx
> +    `Ny event "${event.title}" med ${event.company?.name},
🤓

2024-10-08 11:51 UTC, 0Zeno requested changes
![image](https://github.com/user-attachments/assets/4da64f5e-99d8-42e0-b867-3b9fd75d7182)

2024-10-08 11:51 UTC, 0Zeno commented on apps/web/src/app/(default)/bedpres/[slug]/page.tsx
> +    `Ny bedpress med ${bedpress.company?.name}, ${norwegianDateString(new Date(bedpress.date)).toLowerCase()},
Bedriftspresentasjon?

2024-10-08 11:51 UTC, 0Zeno commented on apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
> +    `Nytt innslag "${post.title}" av ${authorListString}.`,
innlegg?😊

2024-10-08 11:51 UTC, 0Zeno commented on apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
> +    `Ny stilling hos ${jobAd.company.name}, ${jobAd.locations[0]?.name}.`,
stillingsannonse? ☆*: .｡. o(≧▽≦)o .｡.:*☆

2024-10-22 15:09 UTC, 0Zeno submitted a review, later dismissed
<img src="https://media1.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

2024-10-22 16:56 UTC, omfj commented
Ikke merge helt enda. Kan bli gjort litt annerledes.

2024-10-30 06:49 UTC, omfj requested changes
Vi trenger ikke å ha en funksjon for å lage meta tags, siden de vil allerede være der fra root layout sin. Derfor trenger vi bare å overskrive de, der vi vil overskrive de.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/seo.ts
> +import { type TemplateString } from "next/dist/lib/metadata/types/metadata-types";
Trenger ikke denne filen.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/layout.tsx
> -export const metadata = {
Denne kan være som før. Siden metadata satt i root layout vil være på alle sider. Så trenger ikke en egen funksjon for det på de andre sidene, de er der allerede.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/prikker/layout.tsx
> -export const metadata = {
Trenger ikke denne.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/om/vedtekter/page.tsx
> -export const metadata: Metadata = {
Denne kan være som før.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/om/retningslinjer/page.tsx
> -export const metadata: Metadata = {
Denne kan være som før.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/om/brosjyre/page.tsx
> -export const metadata: Metadata = {
Denne kan være som før.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/for-studenter/jobber/page.tsx
> -export const metadata = {
Denne kan være som før. Men legge til en description og.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/for-studenter/jobb/[slug]/page.tsx
> +  );
```suggestion
  return {
    title: jobAd.title,
    description: `Ny stillingsannonse hos ${jobAd.company.name}, ${jobAd.locations[0]?.name}.`,
  };
```

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/for-studenter/innlegg/page.tsx
> +export const metadata = getNewPageMetadata("Innlegg");
Denne kan være som før.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/for-studenter/innlegg/[slug]/page.tsx
> +  return metadata;
```suggestion
  const authorListString = authors?.map((a) => a.name).join(", "); // "Alice, Bob, Charlie"
  const metadata = getNewPageMetadata(
    post.title,
    `Nytt innlegg "${post.title}" av ${authorListString}.`,
  );
  metadata.authors = authors;

  return {
  	title: post.title,
  	description: `Nytt innlegg "${post.title}" av ${authorListString}.`,
  	authors,
  }
```

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/for-studenter/grupper/[groupType]/page.tsx
> +  return getNewPageMetadata(groupName, `En oversikt over echo ${sine} ${groupName.toLowerCase()}.`);
```suggestion
  return {
  	title: groupName,
  	description: `En oversikt over echo ${sine} ${groupName.toLowerCase()}.`,
  	author: groupName
  }
```

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/[...path]/page.tsx
> +  return getNewPageMetadata(page.title);
Denne kan være som før.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/admin/layout.tsx
> +export const metadata = getNewPageMetadata("Admin");
Denne kan være som før.

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/arrangement/[slug]/page.tsx
> +  );
```suggestion
  return {
    title: event.title,
    description: `Nytt arrangement "${event.title}" med ${event.company?.name},
    ${norwegianDateString(new Date(event.date))}, ${event.location?.name}. ${regDate}`,
  };
```

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/bedpres/[slug]/page.tsx
> +  );
```suggestion
  return {
    title: bedpress.title,
    description: `Ny bedriftspresentasjon med ${bedpress.company?.name}, ${norwegianDateString(new Date(bedpress.date)).toLowerCase()},
    ${bedpress.location?.name}. ${regDate}`,
  };
```

2024-10-30 06:49 UTC, omfj commented on apps/web/src/app/(default)/for-studenter/gruppe/[slug]/page.tsx
> +  return getNewPageMetadata(group.name, `Infosiden til echo sin undergruppe ${group.name}.`);
```suggestion
  return {
  	title: group.name,
  	description: `Infosiden til echo sin undergruppe ${group.name}.`
  };
```

2024-12-12 16:44 UTC, omfj approved these changes

2024-12-12 16:49 UTC, merged