Lager registration løsning med "pending" system
echo-webkom/echo-web-mono pull request #998
Opened 2023-12-08 15:51 UTC by kfalvestad

Når en bruker registrerer seg blir status satt til "pending", deretter skjer det en atomisk transaksjon som henter alle registreringer som er "registered", "waiting" eller "pending" (med tidligere createdAt en den nåværende registreringen) og sjekker om dette antallet er større eller lik spotRanges. Hvis den er det så havner brukeren på venteliste, hvis ikke blir brukeren registrert.

2023-12-13 15:06 UTC, omfj requested changes

2023-12-13 15:06 UTC, omfj commented on apps/web/src/actions/register.ts
>      const { isWaitlisted } = resp;
Du kan destructure på linje 162 og under og throw error om `!registration`, om inserten har bæda

2023-12-13 17:11 UTC, omfj commented on packages/db/schemas/registrations.ts
> +    status: registrationStatusEnum("status").notNull().default("pending"),
Er det ikke best å sette rename `reg_id` til bare `id`, og sette den som primary key, og lage en `uniqueIndex("user_id_happening_id_idx").on(table.userId, table.registrationId)`?

2023-12-14 11:04 UTC, kfalvestad commented on packages/db/schemas/registrations.ts
> +    status: registrationStatusEnum("status").notNull().default("pending"),
Jo, enig

2023-12-14 17:56 UTC, merged